export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST';
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS';
export const ARTICLE_LIST_FAILURE = 'ARTICLE_LIST_FAILURE';

export const ARTICLE_DETAILS_REQUEST = 'ARTICLE_DETAILS_REQUEST';
export const ARTICLE_DETAILS_SUCCESS = 'ARTICLE_DETAILS_SUCCESS';
export const ARTICLE_DETAILS_FAILURE = 'ARTICLE_DETAILS_FAILURE';
