export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST';
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS';
export const ARTICLE_LIST_FAILURE = 'ARTICLE_LIST_FAILURE';

export const ARTICLE_DETAILS_REQUEST = 'ARTICLE_DETAILS_REQUEST';
export const ARTICLE_DETAILS_SUCCESS = 'ARTICLE_DETAILS_SUCCESS';
export const ARTICLE_DETAILS_FAILURE = 'ARTICLE_DETAILS_FAILURE';

export const NEW_ARTICLE_REQUEST = 'NEW_ARTICLE_REQUEST';
export const NEW_ARTICLE_SUCCESS = 'NEW_ARTICLE_SUCCESS';
export const NEW_ARTICLE_FAILURE = 'NEW_ARTICLE_FAILURE';

export const LIKE_ARTICLE_REQUEST = 'LIKE_ARTICLE_REQUEST';
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';

export const USER_ARTICLES_REQUEST = 'USER_ARTICLES_REQUEST';
export const USER_ARTICLES_SUCCESS = 'USER_ARTICLES_SUCCESS';
export const USER_ARTICLES_FAILURE = 'USER_ARTICLES_FAILURE';

export const SAVE_ARTICLE_REQUEST = 'SAVE_ARTICLE_REQUEST';
export const SAVE_ARTICLE_SUCCESS = 'SAVE_ARTICLE_SUCCESS';
export const SAVE_ARTICLE_FAILURE = 'SAVE_ARTICLE_FAILURE';

export const GET_SAVED_ARTICLES_REQUEST = 'GET_SAVED_ARTICLES_REQUEST';
export const GET_SAVED_ARTICLES_SUCCESS = 'GET_SAVED_ARTICLES_SUCCESS';
export const GET_SAVED_ARTICLES_FAILURE = 'GET_SAVED_ARTICLES_FAILURE';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';
