export const FEATURED_PODCASTS_REQUEST = 'FEATURED_PODCASTS_REQUEST';
export const FEATURED_PODCASTS_SUCCESS = 'FEATURED_PODCASTS_SUCCESS';
export const FEATURED_PODCASTS_FAILURE = 'FEATURED_PODCASTS_FAILURE';

export const PODCAST_DETAILS_REQUEST = 'PODCAST_DETAILS_REQUEST';
export const PODCAST_DETAILS_SUCCESS = 'PODCAST_DETAILS_SUCCESS';
export const PODCAST_DETAILS_FAILURE = 'PODCAST_DETAILS_FAILURE';

export const PODCAST_EPISODE_DETAILS_REQUEST =
  'PODCAST_EPISODE_DETAILS_REQUEST';
export const PODCAST_EPISODE_DETAILS_SUCCESS =
  'PODCAST_EPISODE_DETAILS_SUCCESS';
export const PODCAST_EPISODE_DETAILS_FAILURE =
  'PODCAST_EPISODE_DETAILS_FAILURE';
