export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';

export const USER_UPDATE_EMAIL_REQUEST = 'USER_UPDATE_EMAIL_REQUEST';
export const USER_UPDATE_EMAIL_SUCCESS = 'USER_UPDATE_EMAIL_SUCCESS';
export const USER_UPDATE_EMAIL_FAILURE = 'USER_UPDATE_EMAIL_FAILURE';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAILURE = 'USER_UPDATE_PASSWORD_FAILURE';

export const ADMIN_ANALYTICS_REQUEST = 'ADMIN_ANALYTICS_REQUEST';
export const ADMIN_ANALYTICS_SUCCESS = 'ADMIN_ANALYTICS_SUCCESS';
export const ADMIN_ANALYTICS_FAILURE = 'ADMIN_ANALYTICS_FAILURE';
